config/routes.rb
Rails.application.routes.draw do

  
  
  root 'pages#home'
  get 'about', to:'pages#about'
  resources :assignments

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 100}
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 100}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  
  before_action :set_assignment, only: [:edit, :update, :show, :destroy]
  
  def index
   @assignments = Assignment.all 
  end
  
  def new
    @assignment = Assignment.new
  end
  
  def edit
  
  end
  
  def create
    
  # render plain: params[:assignments].inspect
  @assignment = Assignment.new(assignment_params)
  
    if @assignment.save
       flash[:success] = "Article was successfully created"
       redirect_to assignment_path(@assignment) #redirect to show action
  
     else
       render 'new'
     end
    end
    
  def update
     
          if @assignment.update(assignment_params)
            flash[:success] = "Article was successfully updated"
            redirect_to assignment_path(@assignment)
          else
            render 'edit'
          end
    end
       

     def show
    
  end
  
  def destroy
   
    @assignment.destroy
    flash[:danger] = "Article was succesfully destroyed"
    redirect_to assignments_path
  end
   private
  
   def set_assignment
      @assignment = Assignment.find(params[:id])
   end
   
         def assignment_params
         params.require(:assignment).permit(:title, :description) 
        end
end

app/controllers/pages_controller.rb
class PagesController<ApplicationController
  
  def home
    
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assignments/_form.html.erb
<%= render 'shared/errors', obj: @assignment %>
<div class='row'>

<div class='col-xs-12'>

<%= form_for(@assignment,:html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :title %>

</div>

<div class="col-sm-8">

<%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :description %>

</div>

<div class="col-sm-8">

<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of assignment" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit class: 'btn btn-primary btn-lg' %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to articles listing", assignments_path%> ]

</div>

</div>

</div>

app/views/assignments/edit.html.erb
<h1 align="center">editing existing assignment</h1>
<%= render 'form' %>

app/views/assignments/index.html.erb
<h1 align = "center"> listing of all assignments </h1>


<% @assignments.each do |f| %>
  <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
     <div class ="assignment-title">
      <%= link_to f.title, assignment_path(f) %>
      </div>
      <div class ="assignment-body">
  <%= truncate(f.description, length:10) %>
  </div>
  <div class="assignment-action">

<%= link_to "Edit", edit_assignment_path(f), class: "btn btn-xs btn-primary" %>
<%= link_to "Destroy", assignment_path(f), method: :delete,
                                         data: { confirm: "Are you sure you want to delete?"}, 
                                         class:"btn btn-xs  btn-danger" %>
                                         </div>
                                         </div>
                                         </div>
                                         </div>
   <% end %>

app/views/assignments/new.html.erb
<h1 align='center'>create an assignment </h1>


<%= render 'form' %>

app/views/assignments/show.html.erb
<h2 align= "center"> Title: <%= @assignment.title %> </h2>

<div class="well col xs-8 col-xs-offset-0">
  <h4 class="center description"><strong>Description</strong></h4>
<hr>
 <%= simple_format(@assignment.description) %>

<div class="assignment-action">

<%= link_to "Edit", edit_assignment_path(@assignment), class: "btn btn-xs btn-primary" %>
<%= link_to "Destroy", assignment_path(@assignment), method: :delete,
                                         data: { confirm: "Are you sure you want to delete?"}, 
                                         class:"btn btn-xs  btn-danger" %>
<%= link_to "View all assignments", assignments_path, class:"btn btn-xs btn-success" %>
</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>
  
Posted by: Anit Jee

Copyright © <a href="anitjee@example.com">anitjee@example.com</a>

</small>

<nav>

<ul>

<li><%= link_to "About", about_path %></li>

</ul>

</nav>

</footer>

</div>

app/views/layouts/_messages.html.erb
<div class= "row">
<div class="col-xs-12 col-xs-offset-0">
</div><% flash.each do |name,msg| %>
<div class ='center alert alert-<%="#{name}"%>'>
<a href = '#' class= "close" data-dismiss="alert">&#215;</a>
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>

</div>

<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
   <%= link_to "Alpha blog", root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%=link_to "Assignments", assignments_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
         <li> <%= link_to "New Assignments",new_assignment_path %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
<div class= "container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<body>

<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
 <%= link_to "Sign up now", "#", class: "btn btn-danger btn-lg btn-xlarge" %>
</div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'></div>
   <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
        <%= pluralize(obj.errors.count, "error") %>
        prohibited this assignment from being saved:
        </h2>
      <div class= "panel-body">
       <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      </div>
    </div>
   </div>
  </div>

<% end %>